spring:
  application:
    name: simple_json_amqp

  config:
    import: optional:file:.env[.properties]

  threads:
    virtual:
      enabled: true

  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT:5672}
    host: ${RABBITMQ_HOST:localhost}
    virtualhost: ${RABBITMQ_VIRTUAL_HOST}

custom:
  rabbitmq:
    exchange: simple_json_exchange
    routing:
      key: simple_json_routing_key
    queue:
      request: simple_json_queue