spring:
  application:
    name: convert_send_and_receive

  threads:
    virtual:
      enabled: true

  config:
    import: optional:file:.env[.properties]

custom:
  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT:5672}
    host: ${RABBITMQ_HOST:localhost}
    virtualhost: ${RABBITMQ_VIRTUAL_HOST}
    queue:
      request: blocking_remote_call_queue
      reply: blocking_remote_call_reply_queue
    exchange: convert_send_and_receive_exchange
    routing:
      key: convert_send_and_receive_routing_key

server:
  error:
    include-message: always
    include-stacktrace: always
  tomcat:
    keep-alive-timeout: 10000