server:
  port: 8081

spring:
  application:
    name: topic_consumer_users

  config:
    import: optional:file:.env[.properties]

  threads:
    virtual:
      enabled: true

custom:
  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT}
    host: ${RABBITMQ_HOST}
    virtualhost: ${RABBITMQ_VIRTUAL_HOST}
    exchange: topic_producer_exchange
    queue:
      users: topic_producer_queue_users