server:
  port: 8081

spring:
  application:
    name: fanout_consumer_one

  config:
    import: optional:file:.env[.properties]

  threads:
    virtual:
      enabled: true

custom:
  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT}
    host: ${RABBITMQ_HOST}
    virtualhost: ${RABBITMQ_VIRTUAL_HOST}
    queue:
      first: fanout_producer_queue_first