server:
  port: 8080
  error:
    include-message: always
    whitelabel:
      enabled: true

spring:
  application:
    name: topic_producer

  config:
    import: optional:file:.env[.properties]

  threads:
    virtual:
      enabled: true

  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT}
    host: ${RABBITMQ_HOST}
    publisher-returns: true
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}

custom:
  rabbitmq:
#    username: ${RABBITMQ_USERNAME}
#    password: ${RABBITMQ_PASSWORD}
#    port: ${RABBITMQ_PORT}
#    host: ${RABBITMQ_HOST}
#    virtualhost: ${RABBITMQ_VIRTUAL_HOST}
    exchange: topic_producer_exchange
    routing_key: topic_producer.events.*