server:
  port: 8081

logging:
  level:
    org.springframework.amqp.rabbit.core.RabbitTemplate: INFO
    org.springframework.amqp.rabbit.connection.CachingConnectionFactory: INFO
    org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer: INFO

spring:
  application:
    name: custom_configuration_consumer

  config:
    import: optional:file:.env[.properties]

  threads:
    virtual:
      enabled: true

  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT:5672}
    host: ${RABBITMQ_HOST:localhost}
    virtualhost: ${RABBITMQ_VIRTUAL_HOST}

custom:
  rabbitmq:
    # In topic exchanges, consumers should use wildcard binding keys
    # to match the routing keys producers actually use
    routing_key: custom_configuration_producer_routing_key.*
    queue: custom_configuration_producer_queue
    exchange: custom_configuration_producer_exchange
