server:
  port: 8081

logging:
  level:
    org.springframework.amqp.rabbit.core.RabbitTemplate: INFO
    org.springframework.amqp.rabbit.connection.CachingConnectionFactory: INFO
    org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer: INFO

spring:
  application:
    name: custom_configuration_consumer

  config:
    import: optional:file:.env[.properties]

  threads:
    virtual:
      enabled: true

custom:
  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT:5672}
    host: ${RABBITMQ_HOST:localhost}
    virtualhost: ${RABBITMQ_VIRTUAL_HOST}
    exchange: simple_json_exchange
    routing:
      key: simple_json_routing_key
    queue:
      request: simple_json_queue
