server:
  port: 8080

spring:
  application:
    name: direct_producer

  config:
    import: optional:file:.env[.properties]

  threads:
    virtual:
      enabled: true

custom:
  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT}
    host: ${RABBITMQ_HOST}
    virtualhost: ${RABBITMQ_VIRTUAL_HOST}
    exchange: direct_producer_exchange
    routing_key: direct_producer_routing_key
    queue: direct_producer_queue