server:
  port: 8083

spring:
  application:
    name: topic_consumer_all

  config:
    import: optional:file:.env[.properties]

  threads:
    virtual:
      enabled: true

custom:
  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT}
    host: ${RABBITMQ_HOST}
    virtualhost: ${RABBITMQ_VIRTUAL_HOST}
    exchange: topic_producer_exchange
    routing_key: topic_producer.events.*
    queue:
      all: topic_producer_queue_all